Important bugfixes for shim-signed-common.postinst
As we're calling grub-install and specifying the target EFI arch, make
sure that we're using the *right* EFI arch. If we're on a mixed-mode
x86 system (32-bit UEFI, 64-bit CPU), that means that we need to be
specifying i386-efi here.

Also check to see if grub-efi has been configured to use
--force-extra-removable or --no-nvram. If we're calling grub-install
here, then it's important we follow the same rules or we may end up
breaking installations. :-/

diff --git a/debian/shim-signed-common.postinst b/debian/shim-signed-common.postinst
--- a/debian/shim-signed-common.postinst
+++ b/debian/shim-signed-common.postinst
@@ -4,20 +4,30 @@ set -e
 # Must load the confmodule for our template to be installed correctly.
 . /usr/share/debconf/confmodule
 
+# Select the right target architecture for grub-install
 ARCH=$(dpkg --print-architecture)
 case ${ARCH} in
-    amd64)
-	GRUB_EFI_TARGET="x86_64-efi";;
-    i386)
-	GRUB_EFI_TARGET="i386-efi";;
+    i386|amd64)
+	FW_SIZE=$(cat /sys/firmware/efi/fw_platform_size)
+	if [ "$FW_SIZE"x = "32"x ]; then
+	    GRUB_EFI_TARGET="i386-efi"
+	elif [ "$FW_SIZE"x = "64"x ]; then
+	    GRUB_EFI_TARGET="x86_64-efi"
+	else
+	    echo "Unable to read a valid value from fw_platform_size, ABORT"
+	    exit 1
+	fi
+	;;
     arm64)
-	GRUB_EFI_TARGET="arm64-efi";;
+	GRUB_EFI_TARGET="arm64-efi"
+	;;
     *)
 	echo "Unsupported dpkg architecture ${ARCH} in $0. ABORT"
 	exit 1
 	;;
 esac
 
+# Pull out a config value from /etc/default/grub
 config_item ()
 {
     if [ -f /etc/default/grub ]; then
@@ -41,10 +51,27 @@ case $1 in
 	case $bootloader_id in
 	    kubuntu) bootloader_id=ubuntu ;;
 	esac
+
+	# Call grub-install to make sure we're added to the ESP as
+	# needed
 	if [ "$bootloader_id" ] && [ -d "/boot/efi/EFI/$bootloader_id" ] \
 	   && which grub-install >/dev/null 2>&1
 	then
-	    grub-install --target=${GRUB_EFI_TARGET}
+	    # Check for some of the options that matter, so we can
+	    # call grub-install safely without dropping them
+	    OPTIONS=""
+
+	    db_get grub2/force_efi_extra_removable
+	    if [ "$RET" = true ]; then
+		OPTIONS="$OPTIONS --force-extra-removable"
+	    fi
+
+	    db_get grub2/update_nvram
+	    if [ "$RET" = false ]; then
+		OPTIONS="$OPTIONS --no-nvram"
+	    fi
+
+	    grub-install --target=${GRUB_EFI_TARGET} $OPTIONS
             if dpkg --compare-versions "$2" lt-nl "1.22~"; then
                 rm -f /boot/efi/EFI/ubuntu/MokManager.efi
             fi
@@ -57,3 +84,4 @@ esac
 #DEBHELPER#
 
 exit 0
+
