Tweak how we call grub-install; don't abort on error
Not ideal behaviour either, but don't break upgrades. Copy the
behaviour from the grub packages here. Closes: #990984

diff --git a/debian/shim-signed.postrm b/debian/shim-signed.postrm
--- a/debian/shim-signed.postrm
+++ b/debian/shim-signed.postrm
@@ -51,6 +51,15 @@ config_item ()
     eval echo "\$$1"
 }
 
+# Call grub-install but don't fail on errors. Let's not break upgrades
+run_grub_install()
+{
+    if ! grub-install $@ ; then
+        echo "Failed: grub-install $@" >&2
+        echo "WARNING: Bootloader is not properly installed, system may not be bootable" >&2
+    fi
+}
+
 case $1 in
     remove|purge)
 	bootloader_id="$(config_item GRUB_DISTRIBUTOR | tr A-Z a-z | \
@@ -79,7 +88,8 @@ case $1 in
 		OPTIONS="$OPTIONS --no-nvram"
 	    fi
 
-	    grub-install --target=${GRUB_EFI_TARGET} $OPTIONS
+	    run_grub_install --target=${GRUB_EFI_TARGET} $OPTIONS
+
             if dpkg --compare-versions "$2" lt-nl "1.22~"; then
                 rm -f /boot/efi/EFI/ubuntu/MokManager.efi
             fi
